### ISSUE TITLE
Allow use with local server (show button bar)

### ISSUE THREAD

**Issue by tonyxiao** [zalmoxisus/atom-redux-devtools#3]
Currently it is impossible to use atom-redux-devtools with a local server due to the fact that button bar is hidden. 

`ReactDOM.render(<DevTools noButtonBar={true} />, root);`

Enabling the button bar causes styling issues in Atom (presumably that's why it's hidden). But it's better than not able to use the tool at all.

![image](https://cloud.githubusercontent.com/assets/696842/15095974/d0866004-1498-11e6-91e3-d42f84deab90.png)

**Comment by zalmoxisus** [comment]
@tonyxiao, yes that is why it is hidden, but I'll try to solve styling issues because now we also have other useful buttons [there](http://remotedev.io/local/): Dispatcher, Import, Export.

**Comment by zalmoxisus** [comment]
`remotedev-app` updated. Should work in `0.2`.
